drop table if exists categorias CASCADE 
drop table if exists preguntas CASCADE 
drop table if exists respuestas CASCADE 
create table categorias (id integer generated by default as identity, nombre varchar(255), puntos integer not null, primary key (id))
create table preguntas (id bigint generated by default as identity, titulo_pregunta varchar(255), id_categoria integer, primary key (id))
create table respuestas (id bigint generated by default as identity, correcta boolean not null, titulo varchar(255), id_pregunta bigint, primary key (id))
alter table preguntas add constraint FKpdyyq7alsnjeernf18d12hyr7 foreign key (id_categoria) references categorias
alter table respuestas add constraint FKhpdeptdk3p3fu5l3i57h9bhn7 foreign key (id_pregunta) references preguntas
